// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTHAEnDZm0yiSOkYtTE22jMYl_gom-PnI',
    appId: '1:600751271596:android:c171fbc1f092bf68eeb909',
    messagingSenderId: '600751271596',
    projectId: 'carrot-market-434412',
    storageBucket: 'carrot-market-434412.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV8yuFMN-GYUmSMuLCmj4EfecpEQ_K9sw',
    appId: '1:600751271596:ios:4d22a6aa3847235aeeb909',
    messagingSenderId: '600751271596',
    projectId: 'carrot-market-434412',
    storageBucket: 'carrot-market-434412.appspot.com',
    androidClientId: '600751271596-j3g61lje0io10scqgmdmiavt3m48hfr4.apps.googleusercontent.com',
    iosClientId: '600751271596-156a8itgbiuq56edjvh8jdsit7i69m4l.apps.googleusercontent.com',
    iosBundleId: 'com.carrot.market',
  );
}
